### PR TITLE
Fix concat ordering

### LINKED ISSUE #14: when using PathFinder the files should preserve their alphabetical order
On line 57 the collected files are converted to a Map:
```
(groupName, r.toMap.values)
```
this results in unpredictable order of concatenation of the matched files and eventually results in JS errors.

The files should be concatenated in their natural (e.g. alphabetical) order - isn't it possible to use the value of ```r```directly ?

### PR DESCRIPTION
**Pull request by LMnet**
Fix #14, read my [comment](https://github.com/ground5hark/sbt-concat/issues/14#issuecomment-121523320)

### CODE REVIEW

**Comment by ground5hark** [comment]
Handled by #15 already

**Comment by mkurz** [comment]
@ground5hark Are you sure you merged the right pull request? #15 uses natural order... Did you read @LMnet's [comment about it](https://github.com/ground5hark/sbt-concat/issues/14#issuecomment-121523320)?

**Comment by LMnet** [comment]
@ground5hark Is there any specific reason why you decided to choose natural ordering?

**Comment by ground5hark** [comment]
Ah I merged the wrong one. Ooops. Going to fix that now.

**Comment by mkurz** [comment]
@ground5hark Thanks! Did you release a new version? Could you git tag it?

**Pull request merged**
